[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
factory = "EHQpL4Q8hMEsufdDR5bsSeSahqt8ShkHbxzPyGsurgR5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/maoma/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"