[solana]
rpc_url="https://api.devnet.solana.com"
ws_url="wss://api.devnet.solana.com"
keypair_path="/Users/maoma/.config/solana/id.json"
commitment="confirmed"
network="devnet"

[oracle]
config_name="terrordemo2"
config_description="this is terror demo"
total_phase=2
authority_pubkey="42taRyQCVHSgeHynMDkomRSRQ26rZ5Ygm2pq7QGmDwnP"
interval=15
program_id="6ULtrYwokDeKTPjArrZYDFQ5yuzZgdZBKCRr2YjyyL22"

[event]
program_id="BdFDKd6ALeLWuF6X52iLBoaEhK29NwtEUAhWv4bwcmjQ"
vision_mining_admin_pubkey="9BCXkJbiftuJCf8mydw7znBr3HmsAydgikYkkPwcqbWG"

[market]
hourly_create=true
daily_create=true

[metadata]
ft_token_name="monitor"
ft_token_symbol="MONI"
ft_token_url="monitare.xyz"
ft_token_decimal=9
sbt_token_name="persona"
sbt_token_symbol="PERSONA"
sbt_token_url="monitare.xyz"
event_metadata_url="monitare.xyz"
fear_sbt_token_name="fear"
fear_sbt_token_symbol="FEAR"
fear_sbt_token_url="monitare.xyz"
greed_sbt_token_name="greed"
greed_sbt_token_symbol="GREED"
greed_sbt_token_url="monitare.xyz"


[tokenomics]
vision_mining = 10000000
event_mining = 60000000
event_prize = 30